# Generated by Django 4.1.1 on 2022-09-18 05:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Facility',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='', max_length=60)),
            ],
        ),
        migrations.RenameField(
            model_name='hospital',
            old_name='City',
            new_name='city',
        ),
        migrations.DeleteModel(
            name='Service',
        ),
    ]
