# Generated by Django 4.1.1 on 2022-09-18 06:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_availability'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='availability',
            name='upadated_at',
        ),
        migrations.AddField(
            model_name='availability',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='availability',
            name='facility',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='availabilies', to='app.facility'),
        ),
    ]
